#!/usr/bin/env bash
# Canonical installer for the `gcp-pricing` CLI. Idempotent. No credentials.
#
# Setup repos call this with one line and carry NO copy of the guidance:
#   curl -fsSL https://raw.githubusercontent.com/WandLZhang/gcp-pricing-scraper/main/install.sh | bash
#
# SKILL.md in this repo is the single source of truth for how an agent should use the tool.
# This script fans it out to whichever harnesses are present on the machine. Duplicating that
# text into each setup repo is what let it go stale: after the engine was rewritten, the Cline
# rule file and the Antigravity GEMINI.md section were still promising a "Source (open to
# verify)" footer and a `sheets` JSON shape that no longer exist.
set -euo pipefail

REPO="git+https://github.com/WandLZhang/gcp-pricing-scraper@main"
RAW="https://raw.githubusercontent.com/WandLZhang/gcp-pricing-scraper/main"
echo "[gcp-pricing] installing CLI..."

if command -v pipx >/dev/null 2>&1; then
  pipx install --force "$REPO"
elif python3 -c 'import ensurepip' >/dev/null 2>&1; then
  APP="$HOME/.local/share/gcp-pricing"
  rm -rf "$APP/venv"
  python3 -m venv "$APP/venv"
  "$APP/venv/bin/pip" install --quiet --upgrade pip
  "$APP/venv/bin/pip" install --quiet "$REPO"
  mkdir -p "$HOME/.local/bin"
  ln -sf "$APP/venv/bin/gcp-pricing" "$HOME/.local/bin/gcp-pricing"
else
  # Debian/PEP-668 externally-managed fallback
  python3 -m pip install --user --break-system-packages --quiet "$REPO"
fi

# ensure ~/.local/bin is on PATH for future shells
mkdir -p "$HOME/.local/bin"
case ":$PATH:" in
  *":$HOME/.local/bin:"*) : ;;
  *) echo 'export PATH="$HOME/.local/bin:$PATH"' >> "$HOME/.bashrc" ;;
esac
# some setups (claude-code) use ~/bin — mirror the launcher there if that dir exists
if [ -d "$HOME/bin" ] && command -v gcp-pricing >/dev/null 2>&1; then
  ln -sf "$(command -v gcp-pricing)" "$HOME/bin/gcp-pricing" 2>/dev/null || true
fi

# ---------------------------------------------------------------- agent guidance, one source

TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT
if ! curl -fsSL "$RAW/SKILL.md" -o "$TMP/SKILL.md" 2>/dev/null; then
  echo "[gcp-pricing] CLI installed; could not fetch SKILL.md (offline?) — agent guidance not updated."
  exit 0
fi
# body = SKILL.md without the YAML frontmatter (harnesses other than Claude Code want prose)
awk 'BEGIN{n=0} /^---$/{n++; next} n>=2' "$TMP/SKILL.md" > "$TMP/BODY.md"

# Claude Code — skill file, frontmatter included
if [ -d "$HOME/.claude" ]; then
  mkdir -p "$HOME/.claude/skills/gcp-pricing"
  cp "$TMP/SKILL.md" "$HOME/.claude/skills/gcp-pricing/SKILL.md"
  echo "  ✓ Claude Code skill"
fi

# Cline — a rule file
for d in "$HOME/Documents/Cline/Rules" "$HOME/.clinerules"; do
  if [ -d "$d" ]; then
    { echo "<!-- generated by gcp-pricing-scraper install.sh — do not edit; edit SKILL.md upstream -->"
      cat "$TMP/BODY.md"; } > "$d/gcp-pricing.md"
    echo "  ✓ Cline rule ($d)"
  fi
done

# Gemini CLI / Antigravity — a delimited section inside GEMINI.md, replaced in place so that
# re-running never duplicates and never drifts.
GEM="${GEMINI_DIR:-$HOME/.gemini}/GEMINI.md"
if [ -f "$GEM" ]; then
  python3 - "$GEM" "$TMP/BODY.md" <<'PY'
import sys, re
path, body = sys.argv[1], open(sys.argv[2]).read().strip()
B, E = "<!-- BEGIN gcp-pricing (generated) -->", "<!-- END gcp-pricing -->"
block = f"{B}\n{body}\n{E}"
cur = open(path).read()
if B in cur and E in cur:
    new = re.sub(re.escape(B) + r".*?" + re.escape(E), lambda _: block, cur, flags=re.S)
else:
    # drop any pre-marker hand-copied section, then insert before Gemini's memories marker
    cur = re.sub(r"\n## GCP pricing \(gcp-pricing CLI\).*?(?=\n## |\Z)", "\n", cur, flags=re.S)
    marker = "## Gemini Added Memories"
    new = (cur.replace(marker, block + "\n\n" + marker, 1) if marker in cur
           else cur.rstrip() + "\n\n" + block + "\n")
open(path, "w").write(new)
PY
  echo "  ✓ Gemini GEMINI.md section"
fi

echo "[gcp-pricing] done. Try: gcp-pricing tpu --filter Trillium"
echo "[gcp-pricing] to upgrade later, re-run this same one-liner."
